import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const SUPABASE_URL='https://gqwhafobiikhhusryqsz.supabase.co';
const SUPABASE_KEY=['sb_publishable_','GH4ld1I2zmd9fM2MpjfjKg','_z_OB94Uj'].join('');
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
let password='',items=[],filter='all',selectedId=null;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const img=p=>supabase.storage.from('contest-photos').getPublicUrl(p).data.publicUrl;
function statusText(s){return s==='pending'?'На модерации':s==='approved'?'Одобрено':'Отклонено'}
async function load(){const{data,error}=await supabase.rpc('admin_list_participants',{p_password:password,p_status:'all'});if(error){password='';$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#loginNote').textContent=error.message;return}items=data||[];renderStats();renderList()}
function renderStats(){$('#allCount').textContent=items.length;$('#pendingCount').textContent=items.filter(x=>x.status==='pending').length;$('#approvedCount').textContent=items.filter(x=>x.status==='approved').length;$('#rejectedCount').textContent=items.filter(x=>x.status==='rejected').length}
function renderList(){const list=items.filter(x=>filter==='all'||x.status===filter);$('#list').innerHTML=list.map(x=>'<div class="request '+(x.id===selectedId?'selected':'')+'" data-id="'+x.id+'"><img src="'+img(x.photo_path)+'" alt=""><div><div class="request-name">'+esc(x.participant_name)+' · '+esc(x.bird_name)+'</div><div class="request-meta">'+esc(x.category)+' · '+new Date(x.created_at).toLocaleString('ru-RU')+'</div><span class="status '+x.status+'">'+statusText(x.status)+'</span></div><div class="request-status"></div></div>').join('')||'<div class="detail-empty">Заявок в этом разделе нет.</div>';document.querySelectorAll('.request').forEach(el=>el.addEventListener('click',()=>{selectedId=el.dataset.id;renderList();renderDetail()}));if(selectedId&&!items.some(x=>x.id===selectedId)){$('#detail').innerHTML='<div class="detail-empty">Выберите заявку слева</div>'}}
function renderDetail(){const x=items.find(i=>i.id===selectedId);if(!x)return;$('#detail').innerHTML='<img class="main-photo" src="'+img(x.photo_path)+'" alt=""><h2>'+esc(x.bird_name)+'</h2><div class="meta"><strong>'+esc(x.participant_name)+'</strong> · '+esc(x.category)+' · '+statusText(x.status)+'</div><div class="story">'+esc(x.description||'История не указана.')+'</div><div class="meta">Подана: '+new Date(x.created_at).toLocaleString('ru-RU')+'<br>Голосов: '+x.vote_count+'</div><div class="actions">'+(x.status!=='approved'?'<button class="approve" id="approveBtn">✓ Одобрить</button>':'')+(x.status!=='rejected'?'<button class="reject" id="rejectBtn">× Отклонить</button>':'')+'</div>';if($('#approveBtn'))$('#approveBtn').onclick=()=>setStatus('approved');if($('#rejectBtn'))$('#rejectBtn').onclick=()=>setStatus('rejected')}
async function setStatus(status){const{error}=await supabase.rpc('admin_set_participant_status',{p_password:password,p_participant_id:selectedId,p_status:status});if(error){alert(error.message);return}const x=items.find(i=>i.id===selectedId);if(x)x.status=status;renderStats();renderList();renderDetail()}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const p=$('#adminPassword').value.trim();$('#loginNote').textContent='Проверяем…';const{data,error}=await supabase.rpc('admin_list_participants',{p_password:p,p_status:'all'});if(error){$('#loginNote').textContent='Неверный пароль или ошибка доступа.';return}password=p;items=data||[];$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');renderStats();renderList()});
document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.status;renderList()}));
$('#refreshBtn').onclick=load;$('#logoutBtn').onclick=()=>{password='';items=[];selectedId=null;$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#adminPassword').value=''};
$('#changePasswordBtn').onclick=()=>$('#passwordModal').classList.remove('hidden');$('#closeModal').onclick=()=>$('#passwordModal').classList.add('hidden');
$('#passwordForm').addEventListener('submit',async e=>{e.preventDefault();const cur=$('#currentPassword').value,newp=$('#newPassword').value;const{error}=await supabase.rpc('admin_change_password',{p_current_password:cur,p_new_password:newp});$('#passwordNote').textContent=error?error.message:'Пароль изменён. Запомните новый пароль.';if(!error){password=newp;setTimeout(()=>{$('#passwordModal').classList.add('hidden');$('#passwordForm').reset();$('#passwordNote').textContent=''},900)}});
