import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const U='https://gqwhafobiikhhusryqsz.supabase.co',K=['sb_publishable_','GH4ld1I2zmd9fM2MpjfjKg','_z_OB94Uj'].join(''),s=createClient(U,K);
let pass='',items=[],filter='all',selected=null;
const $=x=>document.querySelector(x),esc=x=>String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),url=p=>s.storage.from('contest-photos').getPublicUrl(p).data.publicUrl,st=x=>x==='pending'?'На модерации':x==='approved'?'Одобрено':'Отклонено';
function loginView(){pass='';items=[];selected=null;$('#adminDashboard').style.display='none';$('#adminLogin').style.display='grid'}
async function load(){const{data,error}=await s.rpc('admin_list_participants',{p_password:pass,p_status:'all'});if(error){loginView();$('#adminLoginNote').textContent='Сеанс завершён. Войдите снова.';return}items=data||[];stats();list();detail();await loadJuryAdmin()}
function stats(){$('#adminAll').textContent=items.length;$('#adminPending').textContent=items.filter(x=>x.status==='pending').length;$('#adminApproved').textContent=items.filter(x=>x.status==='approved').length;$('#adminRejected').textContent=items.filter(x=>x.status==='rejected').length}
function list(){const a=items.filter(x=>filter==='all'||x.status===filter);$('#adminRequests').innerHTML=a.map(x=>'<div class="admin-request '+(x.id===selected?'selected':'')+'" data-id="'+x.id+'"><img src="'+url(x.photo_path)+'" alt=""><div><div class="admin-request-name">'+esc(x.participant_name)+' · '+esc(x.bird_name)+'</div><div class="admin-request-meta">'+esc(x.category)+' · '+new Date(x.created_at).toLocaleString('ru-RU')+'</div><span class="admin-status '+x.status+'">'+st(x.status)+'</span></div></div>').join('')||'<div class="admin-empty">Заявок в этом разделе нет.</div>';document.querySelectorAll('.admin-request').forEach(e=>e.onclick=()=>{selected=e.dataset.id;list();detail()})}
function detail(){const x=items.find(i=>i.id===selected);if(!x){$('#adminDetail').innerHTML='<div class="admin-empty">Выберите заявку слева</div>';return}$('#adminDetail').innerHTML='<img src="'+url(x.photo_path)+'" alt=""><h3>'+esc(x.bird_name)+'</h3><div class="admin-muted"><strong>'+esc(x.participant_name)+'</strong> · '+esc(x.category)+' · '+st(x.status)+'</div><p>'+esc(x.description||'История не указана.')+'</p><div class="admin-muted">Подана: '+new Date(x.created_at).toLocaleString('ru-RU')+'<br>Голосов: '+x.vote_count+'</div><div class="admin-actions">'+(x.status!=='approved'?'<button class="ok" id="adminApprove">✓ Одобрить</button>':'')+(x.status!=='rejected'?'<button class="no" id="adminReject">× Отклонить</button>':'')+(x.status==='rejected'?'<button class="danger" id="adminDelete">🗑 Удалить</button>':'')+'</div>';if($('#adminApprove'))$('#adminApprove').onclick=()=>setStatus('approved');if($('#adminReject'))$('#adminReject').onclick=()=>setStatus('rejected');if($('#adminDelete'))$('#adminDelete').onclick=deleteRejected}
async function setStatus(status){const{error}=await s.rpc('admin_set_participant_status',{p_password:pass,p_participant_id:selected,p_status:status});if(error){alert(error.message);return}const x=items.find(i=>i.id===selected);if(x)x.status=status;stats();list();detail()}
$('#adminLoginForm').addEventListener('submit',async e=>{e.preventDefault();const p=$('#adminPasswordInput').value.trim();$('#adminLoginNote').textContent='Проверяем…';const{data,error}=await s.rpc('admin_list_participants',{p_password:p,p_status:'all'});if(error){$('#adminLoginNote').textContent='Неверный пароль или ошибка доступа.';return}pass=p;items=data||[];$('#adminLogin').style.display='none';$('#adminDashboard').style.display='block';stats();list();await loadJuryAdmin()});
document.querySelectorAll('.admin-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.status;list()});
$('#adminRefresh').onclick=load;$('#adminLogout').onclick=loginView;$('#adminClose').onclick=()=>{$('#adminModal').classList.remove('open');loginView()};$('#adminOpen').onclick=e=>{e.preventDefault();$('#adminModal').classList.add('open');$('#adminLoginNote').textContent='';setTimeout(()=>$('#adminPasswordInput').focus(),50)};$('#adminModal').onclick=e=>{if(e.target.id==='adminModal')$('#adminClose').click()};

$('#adminChangePassword').onclick=()=>{$('#adminPasswordModal').classList.add('open');$('#adminPasswordNote').textContent='';$('#adminCurrentPassword').focus()};
$('#adminPasswordCancel').onclick=()=>{$('#adminPasswordModal').classList.remove('open');$('#adminPasswordForm').reset()};
$('#adminPasswordModal').onclick=e=>{if(e.target.id==='adminPasswordModal')$('#adminPasswordCancel').click()};
$('#adminPasswordForm').addEventListener('submit',async e=>{e.preventDefault();const cur=$('#adminCurrentPassword').value,newp=$('#adminNewPassword').value,newp2=$('#adminNewPassword2').value;const note=$('#adminPasswordNote');if(newp.length<8){note.textContent='Новый пароль должен содержать не менее 8 символов.';return}if(newp!==newp2){note.textContent='Новые пароли не совпадают.';return}note.textContent='Сохраняем…';const{error}=await s.rpc('admin_change_password',{p_current_password:cur,p_new_password:newp});if(error){note.textContent='Не удалось изменить пароль: '+error.message;return}pass=newp;note.textContent='Пароль успешно изменён.';setTimeout(()=>{$('#adminPasswordCancel').click()},700)});

async function deleteRejected(){if(!selected)return;if(!confirm('Удалить отклонённую заявку и её фотографию безвозвратно?'))return;const{data,error}=await s.rpc('admin_delete_participant',{p_password:pass,p_participant_id:selected});if(error){alert(error.message);return}if(data?.photo_path)await s.storage.from('contest-photos').remove([data.photo_path]);items=items.filter(x=>x.id!==selected);selected=null;stats();list();detail()}
async function adminApi(body){const{data,error}=await s.functions.invoke('judge-api',{body});if(error)throw error;return data}
async function loadJuryAdmin(){try{const cur=await s.from('contest_settings').select('winners_enabled').eq('id',true).single();$('#adminWinnersToggle').checked=!!cur.data?.winners_enabled;const r=await adminApi({action:'admin_judges',password:pass});renderJudges(r.items||[]);const sum=await loadSummary();}catch(e){console.error(e)}}
function renderJudges(list){$('#adminJudgesList').innerHTML=list.map(j=>'<div class="admin-judge-row"><div><strong>'+esc(j.judge_name)+'</strong><span>'+esc(j.login)+'</span></div><div class="admin-judge-actions"><button class="admin-ghost judge-pass" data-id="'+j.id+'">Изменить пароль</button><button class="admin-ghost danger judge-del" data-id="'+j.id+'">Удалить</button></div></div>').join('')||'<div class="admin-empty">Судьи ещё не добавлены.</div>';document.querySelectorAll('.judge-pass').forEach(b=>b.onclick=async()=>{const pw=prompt('Новый пароль судьи (не менее 8 символов):');if(!pw)return;try{const r=await adminApi({action:'admin_change_judge_password',password:pass,judge_id:b.dataset.id,new_password:pw});if(r.error)throw new Error(r.error);alert('Пароль судьи изменён.')}catch(e){alert(e.message)}});document.querySelectorAll('.judge-del').forEach(b=>b.onclick=async()=>{if(!confirm('Удалить этого судью? Его оценки также будут удалены.'))return;try{const r=await adminApi({action:'admin_delete_judge',password:pass,judge_id:b.dataset.id});if(r.error)throw new Error(r.error);loadJuryAdmin()}catch(e){alert(e.message)}})}
async function loadSummary(){const {data,error}=await s.rpc('admin_judge_summary',{p_password:pass});if(error)throw error;$('#adminJudgeSummary').innerHTML=(data||[]).map(x=>'<div class="summary-row"><strong>'+esc(x.bird_name)+'</strong><span>'+esc(x.participant_name)+' · '+esc(x.category)+'</span><b>'+x.judge_average+'/10</b><small>'+x.total_scores+' оценок судей · '+x.vote_count+' голосов зрителей</small></div>').join('')||'<div class="admin-empty">Оценок пока нет.</div>';return data}
$('#adminWinnersToggle').onchange=async()=>{try{const r=await adminApi({action:'admin_winners',password:pass,enabled:$('#adminWinnersToggle').checked});if(r.error)throw new Error(r.error);await loadWinners()}catch(e){alert(e.message);$('#adminWinnersToggle').checked=!$('#adminWinnersToggle').checked}};
$('#addJudge').onclick=async()=>{const name=$('#newJudgeName').value.trim(),login=$('#newJudgeLogin').value.trim(),pw=$('#newJudgePassword').value;if(!name||!login||pw.length<8){alert('Заполните имя, логин и пароль не менее 8 символов.');return}try{const r=await adminApi({action:'admin_add_judge',password:pass,name,login,new_password:pw});if(r.error)throw new Error(r.error);$('#newJudgeName').value='';$('#newJudgeLogin').value='';$('#newJudgePassword').value='';await loadJuryAdmin();alert('Судья добавлен.')}catch(e){alert(e.message)}};
