import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const U='https://gqwhafobiikhhusryqsz.supabase.co',K=['sb_publishable_','GH4ld1I2zmd9fM2MpjfjKg','_z_OB94Uj'].join(''),s=createClient(U,K);
let pass='',items=[],filter='all',selected=null;
const $=x=>document.querySelector(x),esc=x=>String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),url=p=>s.storage.from('contest-photos').getPublicUrl(p).data.publicUrl,st=x=>x==='pending'?'На модерации':x==='approved'?'Одобрено':'Отклонено';
function loginView(){pass='';items=[];selected=null;$('#adminDashboard').style.display='none';$('#adminLogin').style.display='grid'}
async function load(){const{data,error}=await s.rpc('admin_list_participants',{p_password:pass,p_status:'all'});if(error){loginView();$('#adminLoginNote').textContent='Сеанс завершён. Войдите снова.';return}items=data||[];stats();list();detail()}
function stats(){$('#adminAll').textContent=items.length;$('#adminPending').textContent=items.filter(x=>x.status==='pending').length;$('#adminApproved').textContent=items.filter(x=>x.status==='approved').length;$('#adminRejected').textContent=items.filter(x=>x.status==='rejected').length}
function list(){const a=items.filter(x=>filter==='all'||x.status===filter);$('#adminRequests').innerHTML=a.map(x=>'<div class="admin-request '+(x.id===selected?'selected':'')+'" data-id="'+x.id+'"><img src="'+url(x.photo_path)+'" alt=""><div><div class="admin-request-name">'+esc(x.participant_name)+' · '+esc(x.bird_name)+'</div><div class="admin-request-meta">'+esc(x.category)+' · '+new Date(x.created_at).toLocaleString('ru-RU')+'</div><span class="admin-status '+x.status+'">'+st(x.status)+'</span></div></div>').join('')||'<div class="admin-empty">Заявок в этом разделе нет.</div>';document.querySelectorAll('.admin-request').forEach(e=>e.onclick=()=>{selected=e.dataset.id;list();detail()})}
function detail(){const x=items.find(i=>i.id===selected);if(!x){$('#adminDetail').innerHTML='<div class="admin-empty">Выберите заявку слева</div>';return}$('#adminDetail').innerHTML='<img src="'+url(x.photo_path)+'" alt=""><h3>'+esc(x.bird_name)+'</h3><div class="admin-muted"><strong>'+esc(x.participant_name)+'</strong> · '+esc(x.category)+' · '+st(x.status)+'</div><p>'+esc(x.description||'История не указана.')+'</p><div class="admin-muted">Подана: '+new Date(x.created_at).toLocaleString('ru-RU')+'<br>Голосов: '+x.vote_count+'</div><div class="admin-actions">'+(x.status!=='approved'?'<button class="ok" id="adminApprove">✓ Одобрить</button>':'')+(x.status!=='rejected'?'<button class="no" id="adminReject">× Отклонить</button>':'')+'</div>';if($('#adminApprove'))$('#adminApprove').onclick=()=>setStatus('approved');if($('#adminReject'))$('#adminReject').onclick=()=>setStatus('rejected')}
async function setStatus(status){const{error}=await s.rpc('admin_set_participant_status',{p_password:pass,p_participant_id:selected,p_status:status});if(error){alert(error.message);return}const x=items.find(i=>i.id===selected);if(x)x.status=status;stats();list();detail()}
$('#adminLoginForm').addEventListener('submit',async e=>{e.preventDefault();const p=$('#adminPasswordInput').value.trim();$('#adminLoginNote').textContent='Проверяем…';const{data,error}=await s.rpc('admin_list_participants',{p_password:p,p_status:'all'});if(error){$('#adminLoginNote').textContent='Неверный пароль или ошибка доступа.';return}pass=p;items=data||[];$('#adminLogin').style.display='none';$('#adminDashboard').style.display='block';stats();list()});
document.querySelectorAll('.admin-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.status;list()});
$('#adminRefresh').onclick=load;$('#adminLogout').onclick=loginView;$('#adminClose').onclick=()=>{$('#adminModal').classList.remove('open');loginView()};$('#adminOpen').onclick=e=>{e.preventDefault();$('#adminModal').classList.add('open');$('#adminLoginNote').textContent='';setTimeout(()=>$('#adminPasswordInput').focus(),50)};$('#adminModal').onclick=e=>{if(e.target.id==='adminModal')$('#adminClose').click()};
