import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const U='https://gqwhafobiikhhusryqsz.supabase.co',K=['sb_publishable_','GH4ld1I2zmd9fM2MpjfjKg','_z_OB94Uj'].join(''),s=createClient(U,K);
let token='',judge=null,items=[];
const $=x=>document.querySelector(x),esc=x=>String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"&apos;":'&#39;','"':'&quot;',"'":'&#39;'}[c])),url=p=>s.storage.from('contest-photos').getPublicUrl(p).data.publicUrl;
async function api(body){const{data,error}=await s.functions.invoke('judge-api',{body});if(error)return{data:null,error};return{data,error:null}}
function open(){ $('#judgeModal').classList.add('open');$('#judgeModal').setAttribute('aria-hidden','false'); if(token)showDashboard(); else {$('#judgeLogin').style.display='grid';$('#judgeDashboard').style.display='none';setTimeout(()=>$('#judgeLoginInput').focus(),50)}}
function close(){$('#judgeModal').classList.remove('open');$('#judgeModal').setAttribute('aria-hidden','true');logout(true)}
async function logout(silent=false){if(token){await api({action:'logout',token}).catch(()=>{})}token='';judge=null;items=[];$('#judgeDashboard').style.display='none';$('#judgeLogin').style.display='grid';$('#judgeLoginForm').reset();if(!silent)$('#judgeLoginNote').textContent='Вы вышли из кабинета судьи.'}
async function login(e){e.preventDefault();const login=$('#judgeLoginInput').value.trim(),password=$('#judgePasswordInput').value;$('#judgeLoginNote').textContent='Проверяем…';const r=await api({action:'login',login,password});if(r.error||!r.data?.token){$('#judgeLoginNote').textContent='Неверный логин или пароль.';return}token=r.data.token;judge=r.data.judge;$('#judgeLoginNote').textContent='';$('#judgeLogin').style.display='none';$('#judgeDashboard').style.display='block';$('#judgeWho').textContent='Вы вошли как '+judge.name+' ('+judge.login+')';await load()}
async function load(){if(!token)return;const r=await api({action:'list',token});if(r.error||!r.data){token='';judge=null;$('#judgeDashboard').style.display='none';$('#judgeLogin').style.display='grid';$('#judgeLoginNote').textContent='Сеанс истёк. Войдите снова.';return}items=r.data.participants||[];render()}
function selectHtml(value){const has=Number.isInteger(Number(value))&&Number(value)>=1&&Number(value)<=10;return '<option value="" '+(has?'':'selected')+' disabled>—</option>'+Array.from({length:10},(_,i)=>{const n=i+1;return '<option value="'+n+'" '+(Number(value)===n?'selected':'')+'>'+n+'</option>'}).join('')}
function render(){const box=$('#judgeRequests');box.innerHTML=items.map(p=>{const sc=p.score||{};const keys=['breed_match','photo_quality','pose_naturalness','plumage_condition','composition','overall_impression'];const avg=keys.every(k=>Number.isInteger(Number(sc[k])))?[(keys.reduce((sum,k)=>sum+Number(sc[k]),0)/6).toFixed(2)]:['—'];return '<article class="judge-card" data-id="'+p.id+'"><img class="judge-card-photo" src="'+url(p.photo_path)+'" alt="'+esc(p.bird_name)+'"><div class="judge-card-body"><h3>'+esc(p.bird_name||'Без имени')+'</h3><div class="judge-card-meta">'+esc(p.participant_name||'Участник')+' · '+esc(p.category||'Общий конкурс')+'</div><div class="judge-score-grid"><label class="judge-score">Соответствие породе и породным признакам<select data-field="breed_match">'+selectHtml(sc.breed_match)+'</select></label><label class="judge-score">Качество фото (чёткость, резкость, освещение)<select data-field="photo_quality">'+selectHtml(sc.photo_quality)+'</select></label><label class="judge-score">Удачный ракурс и естественность позы<select data-field="pose_naturalness">'+selectHtml(sc.pose_naturalness)+'</select></label><label class="judge-score">Состояние оперения и внешний вид<select data-field="plumage_condition">'+selectHtml(sc.plumage_condition)+'</select></label><label class="judge-score">Композиция и минимализм декораций<select data-field="composition">'+selectHtml(sc.composition)+'</select></label><label class="judge-score">Общее впечатление<select data-field="overall_impression">'+selectHtml(sc.overall_impression)+'</select></label></div><textarea class="judge-comment" data-field="comment" maxlength="1000" placeholder="Комментарий судьи">'+esc(sc.comment||'')+'</textarea><div class="judge-total">Средняя оценка: <span class="judge-avg">'+avg+'</span> / 10</div><button class="judge-save">Сохранить оценку</button><div class="judge-saved">'+(sc.updated_at?'Сохранено '+new Date(sc.updated_at).toLocaleString('ru-RU'):'Оценка ещё не сохранена')+'</div></div></article>'}).join('')||'<div class="judge-empty">Пока нет допущенных фотографий для судейства.</div>';document.querySelectorAll('.judge-save').forEach(b=>b.onclick=()=>save(b));document.querySelectorAll('.judge-card select').forEach(x=>x.onchange=()=>updateAvg(x.closest('.judge-card')));document.querySelectorAll('.judge-card-photo').forEach(img=>img.onclick=()=>openJudgePhoto(img));}
function updateAvg(card){const raw=['breed_match','photo_quality','pose_naturalness','plumage_condition','composition','overall_impression'].map(k=>card.querySelector('[data-field="'+k+'"]').value);card.querySelector('.judge-avg').textContent=raw.every(v=>v)?(raw.reduce((a,b)=>a+Number(b),0)/6).toFixed(2):'—'}
async function save(btn){const card=btn.closest('.judge-card'),id=card.dataset.id;btn.disabled=true;btn.textContent='Сохраняем…';const body={action:'score',token,participant_id:id};card.querySelectorAll('[data-field]').forEach(el=>body[el.dataset.field]=el.value);const r=await api(body);if(r.error||!r.data?.ok){btn.textContent='Ошибка';alert(r.error?.message||r.data?.error||'Не удалось сохранить оценку.');btn.disabled=false;return}const p=items.find(x=>x.id===id);if(p)p.score=r.data.score;btn.textContent='✓ Сохранено';card.querySelector('.judge-saved').textContent='Сохранено '+new Date(r.data.score.updated_at).toLocaleString('ru-RU');setTimeout(()=>{btn.textContent='Сохранить оценку';btn.disabled=false},900)}
function openJudgePhoto(img){$('#photoLightboxImage').src=img.src;$('#photoLightboxImage').alt=img.alt;const p=items.find(x=>x.id===img.closest('.judge-card').dataset.id);$('#photoLightboxTitle').textContent=p?.bird_name||'';$('#photoLightboxMeta').textContent=(p?.participant_name||'Участник')+' · '+(p?.category||'');$('#photoLightbox').classList.add('open');$('#photoLightbox').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
$('#judgesOpen').addEventListener('click',e=>{e.preventDefault();open()});$('#judgeLoginForm').addEventListener('submit',login);$('#judgeRefresh').onclick=load;$('#judgeLogout').onclick=()=>logout();$('#judgeClose').onclick=close;$('#judgeModal').onclick=e=>{if(e.target.id==='judgeModal')close()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#judgeModal').classList.contains('open'))close()});
