import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const SUPABASE_URL='https://gqwhafobiikhhusryqsz.supabase.co';
const SUPABASE_KEY=['sb_publishable_','GH4ld1I2zmd9fM2MpjfjKg','_z_OB94Uj'].join('');
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const CANARY_PHOTOS=[
{id:'demo-1',name:'Солнечный Ричи',author:'Елена М.',category:'Портрет',votes:12,image:'https://images.unsplash.com/photo-1540554341341-f9134ca0df1a?auto=format&fit=crop&w=900&q=85'},
{id:'demo-2',name:'Жёлтая красавица',author:'Игорь П.',category:'Яркий окрас',votes:9,image:'https://images.unsplash.com/photo-1654181920354-5c4add3989a1?auto=format&fit=crop&w=900&q=85'},
{id:'demo-3',name:'Утро в клетке',author:'Марина К.',category:'Домашний любимец',votes:7,image:'https://images.unsplash.com/photo-1708204931288-e424bde77d8f?auto=format&fit=crop&w=900&q=85'},
{id:'demo-4',name:'Золотой портрет',author:'Сергей В.',category:'Портрет',votes:5,image:'https://images.unsplash.com/photo-1540554341341-f9134ca0df1a?auto=format&fit=crop&w=900&q=85'},
{id:'demo-5',name:'Яркое перо',author:'Наталья Р.',category:'Яркий окрас',votes:4,image:'https://images.unsplash.com/photo-1654181920354-5c4add3989a1?auto=format&fit=crop&w=900&q=85'},
{id:'demo-6',name:'Любимая канарейка',author:'Алексей Т.',category:'Домашний любимец',votes:3,image:'https://images.unsplash.com/photo-1708204931288-e424bde77d8f?auto=format&fit=crop&w=900&q=85'}];
let participants=[],currentFilter='all';
const galleryGrid=document.querySelector('#galleryGrid'),leaderboard=document.querySelector('#leaderboard'),note=document.querySelector('#formNote');
const publicPhotoUrl=p=>supabase.storage.from('contest-photos').getPublicUrl(p).data.publicUrl;
const voterKey=(()=>{let k=localStorage.getItem('canary_voter_key');if(!k){k=crypto.randomUUID();localStorage.setItem('canary_voter_key',k)}return k})();
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function allPhotos(){return [...participants.map(p=>({id:p.id,name:p.bird_name||'Без имени',author:p.participant_name||'Участник',category:p.category||'Общий конкурс',votes:p.vote_count||0,image:publicPhotoUrl(p.photo_path)})),...CANARY_PHOTOS]}
function renderGallery(){const list=allPhotos().filter(p=>currentFilter==='all'||p.category===currentFilter);galleryGrid.innerHTML=list.map(p=>'<article class="photo-card"><button class="photo-open" data-photo-id="'+p.id+'" aria-label="Открыть фото '+escapeHtml(p.name)+'"><img loading="lazy" src="'+p.image+'" alt="'+escapeHtml(p.name)+'"></button><div class="photo-body"><div class="photo-meta"><div><div class="photo-title">'+escapeHtml(p.name)+'</div><div class="photo-category">'+escapeHtml(p.author)+' · '+escapeHtml(p.category)+'</div></div>'+(p.id.startsWith('demo-')?'':'<button class="vote" data-id="'+p.id+'">♥ <span>'+p.votes+'</span></button>')+'</div></div></article>').join('')||'<div class="empty">В этой категории пока нет фотографий.</div>';document.querySelectorAll('.vote').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();vote(b)}));document.querySelectorAll('.photo-open').forEach(b=>b.addEventListener('click',()=>openPhoto(b.dataset.photoId)))}
function openPhoto(id){const p=allPhotos().find(x=>x.id===id);if(!p)return;document.querySelector('#photoLightboxImage').src=p.image;document.querySelector('#photoLightboxImage').alt=p.name;document.querySelector('#photoLightboxTitle').textContent=p.name;document.querySelector('#photoLightboxMeta').textContent=p.author+' · '+p.category+' · '+p.votes+' голосов';document.querySelector('#photoLightbox').classList.add('open');document.querySelector('#photoLightbox').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closePhoto(){document.querySelector('#photoLightbox').classList.remove('open');document.querySelector('#photoLightbox').setAttribute('aria-hidden','true');document.querySelector('#photoLightboxImage').src='';document.body.style.overflow=''}
document.querySelector('#photoLightboxClose').addEventListener('click',closePhoto);document.querySelector('#photoLightbox').addEventListener('click',e=>{if(e.target.id==='photoLightbox')closePhoto()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closePhoto()})
function renderLeaderboard(){leaderboard.innerHTML=participants.slice().sort((a,b)=>(b.vote_count||0)-(a.vote_count||0)).slice(0,4).map(p=>({id:p.id,name:p.bird_name||'Без имени',author:p.participant_name||'Участник',category:p.category||'Общий конкурс',votes:p.vote_count||0,image:publicPhotoUrl(p.photo_path)})).map((p,i)=>'<div class="leader"><div class="rank">0'+(i+1)+'</div><img loading="lazy" src="'+p.image+'" alt=""><div><div class="leader-name">'+escapeHtml(p.name)+'</div><div class="leader-votes">'+escapeHtml(p.author)+'</div></div><strong>'+p.votes+' ♥</strong></div>').join('')}
async function vote(btn){btn.disabled=true;const{error}=await supabase.from('votes').insert({participant_id:btn.dataset.id,voter_key:voterKey});if(error){note.textContent=error.code==='23505'?'Вы уже голосовали за эту фотографию.':'Не удалось принять голос. Попробуйте ещё раз.';btn.disabled=false;return}const p=participants.find(x=>x.id===btn.dataset.id);if(p)p.vote_count=(p.vote_count||0)+1;btn.querySelector('span').textContent=p?.vote_count||1;btn.classList.add('voted');renderLeaderboard()}
async function loadParticipants(){const{data,error}=await supabase.from('participants').select('*').eq('status','approved').order('vote_count',{ascending:false});if(error){console.error(error);return}participants=data||[];renderGallery();renderLeaderboard();const count=document.querySelector('#participantCount');if(count)count.textContent=participants.length}
document.querySelector('#filterBtn').addEventListener('click',()=>document.querySelector('#filterMenu').classList.toggle('open'));
document.querySelectorAll('#filterMenu button').forEach(b=>b.addEventListener('click',()=>{currentFilter=b.dataset.filter;document.querySelector('#filterMenu').classList.remove('open');document.querySelector('#filterBtn').innerHTML=b.textContent+' <span>⌄</span>';renderGallery()}));
document.querySelector('#entryForm').addEventListener('submit',async e=>{e.preventDefault();note.textContent='Отправляем фотографию…';const form=e.currentTarget,file=form.photo.files[0];if(!file){note.textContent='Выберите фотографию.';return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){note.textContent='Допустимы JPG, PNG и WEBP.';return}if(file.size>10*1024*1024){note.textContent='Файл должен быть не больше 10 МБ.';return}const ext=file.name.split('.').pop().toLowerCase(),path='submissions/'+crypto.randomUUID()+'.'+ext;const upload=await supabase.storage.from('contest-photos').upload(path,file,{contentType:file.type,upsert:false});if(upload.error){note.textContent='Не удалось загрузить фото: '+upload.error.message;return}const fd=new FormData(form),{error}=await supabase.from('participants').insert({participant_name:fd.get('name'),bird_name:fd.get('bird'),category:fd.get('category'),description:fd.get('story')||null,photo_path:path,status:'pending',vote_count:0});if(error){await supabase.storage.from('contest-photos').remove([path]);note.textContent='Не удалось сохранить заявку: '+error.message;return}form.reset();note.textContent='Спасибо! Заявка сохранена и появится в галерее после проверки модератором.'});
renderGallery();renderLeaderboard();loadParticipants();
async function loadWinners(){try{const{data,error}=await supabase.functions.invoke('judge-api',{body:{action:'winners'}});if(error||!data?.enabled){document.querySelector('#winners').style.display='none';document.querySelector('#winnersNav').style.display='none';return}document.querySelector('#winners').style.display='block';document.querySelector('#winnersNav').style.display='inline-flex';const g=document.querySelector('#winnersGrid');g.innerHTML=(data.items||[]).map((p,i)=>'<article class="winner-card"><div class="winner-place">Место '+(i+1)+'</div><img src="'+publicPhotoUrl(p.photo_path)+'" alt="'+escapeHtml(p.bird_name||'')+'"><div class="winner-body"><h3>'+escapeHtml(p.bird_name||'Без имени')+'</h3><p>'+escapeHtml(p.participant_name||'Участник')+' · '+escapeHtml(p.category||'')+'</p><strong>'+p.judge_average+'/10</strong><span>'+p.total_scores+' оценок жюри · '+p.vote_count+' голосов зрителей</span></div></article>').join('')||'<div class="empty">Итоги жюри пока не опубликованы.</div>'}catch(e){console.error(e)}}
loadWinners();
