import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const SUPABASE_URL='https://gqwhafobiikhhusryqsz.supabase.co';
const SUPABASE_KEY=['sb_publishable_','GH4ld1I2zmd9fM2MpjfjKg','_z_OB94Uj'].join('');
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const CANARY_PHOTOS=[];
let participants=[],currentFilter='all';
const galleryGrid=document.querySelector('#galleryGrid'),leaderboard=document.querySelector('#leaderboard'),note=document.querySelector('#formNote');
const publicPhotoUrl=p=>supabase.storage.from('contest-photos').getPublicUrl(p).data.publicUrl;
const voterKey=(()=>{let k=localStorage.getItem('canary_voter_key');if(!k){k=crypto.randomUUID();localStorage.setItem('canary_voter_key',k)}return k})();
let currentDailyVote=null;
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function allPhotos(){return [...participants.map(p=>({id:p.id,name:p.bird_name||'Без имени',author:p.participant_name||'Участник',category:p.category||'Общий конкурс',votes:p.vote_count||0,image:publicPhotoUrl(p.photo_path)})),...CANARY_PHOTOS]}
function renderGallery(){const list=allPhotos().filter(p=>currentFilter==='all'||p.category===currentFilter);galleryGrid.innerHTML=list.map(p=>'<article class="photo-card"><button class="photo-open" data-photo-id="'+p.id+'" aria-label="Открыть фото '+escapeHtml(p.name)+'"><img loading="lazy" src="'+p.image+'" alt="'+escapeHtml(p.name)+'"></button><div class="photo-body"><div class="photo-meta"><div><div class="photo-title">'+escapeHtml(p.name)+'</div><div class="photo-category">'+escapeHtml(p.author)+' · '+escapeHtml(p.category)+'</div></div>'+(p.id.startsWith('demo-')?'':'<button class="vote'+(currentDailyVote===p.id?' voted':'')+'" data-id="'+p.id+'" aria-pressed="'+(currentDailyVote===p.id?'true':'false')+'" title="'+(currentDailyVote===p.id?'Отменить лайк':'Поставить лайк за эту фотографию')+'">'+(currentDailyVote===p.id?'♥':'♡')+' <span>'+p.votes+'</span></button>')+'</div></div></article>').join('')||'<div class="empty">В этой категории пока нет фотографий.</div>';document.querySelectorAll('.vote').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();vote(b)}));document.querySelectorAll('.photo-open').forEach(b=>b.addEventListener('click',()=>openPhoto(b.dataset.photoId)))}
function openPhoto(id){const p=allPhotos().find(x=>x.id===id);if(!p)return;document.querySelector('#photoLightboxImage').src=p.image;document.querySelector('#photoLightboxImage').alt=p.name;document.querySelector('#photoLightboxTitle').textContent=p.name;document.querySelector('#photoLightboxMeta').textContent=p.author+' · '+p.category+' · '+p.votes+' голосов';document.querySelector('#photoLightbox').classList.add('open');document.querySelector('#photoLightbox').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closePhoto(){document.querySelector('#photoLightbox').classList.remove('open');document.querySelector('#photoLightbox').setAttribute('aria-hidden','true');document.querySelector('#photoLightboxImage').src='';document.body.style.overflow=''}
document.querySelector('#photoLightboxClose').addEventListener('click',closePhoto);document.querySelector('#photoLightbox').addEventListener('click',e=>{if(e.target.id==='photoLightbox')closePhoto()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closePhoto()})
function renderLeaderboard(){leaderboard.innerHTML=participants.slice().sort((a,b)=>(b.vote_count||0)-(a.vote_count||0)).slice(0,4).map(p=>({id:p.id,name:p.bird_name||'Без имени',author:p.participant_name||'Участник',category:p.category||'Общий конкурс',votes:p.vote_count||0,image:publicPhotoUrl(p.photo_path)})).map((p,i)=>'<div class="leader"><div class="rank">0'+(i+1)+'</div><img loading="lazy" src="'+p.image+'" alt=""><div><div class="leader-name">'+escapeHtml(p.name)+'</div><div class="leader-votes">'+escapeHtml(p.author)+'</div></div><strong>'+p.votes+' ♥</strong></div>').join('')}
async function vote(btn){btn.disabled=true;const id=btn.dataset.id;try{if(currentDailyVote===id){const{data,error}=await supabase.rpc('remove_daily_vote',{p_voter_key:voterKey});if(error)throw error;if(data?.status==='removed'){note.textContent='Лайк отменён. Сегодня вы можете выбрать другую фотографию.';currentDailyVote=null}}else{if(currentDailyVote&&!window.confirm('Вы уже поставили лайк другой фотографии сегодня. Перенести ваш лайк на эту фотографию?')){btn.disabled=false;return}const{data,error}=await supabase.rpc('set_daily_vote',{p_participant_id:id,p_voter_key:voterKey});if(error)throw error;currentDailyVote=id;note.textContent=data?.status==='switched'?'Лайк перенесён на выбранную фотографию.':'Ваш лайк принят. Сегодня можно поддержать только одну фотографию.'}await loadParticipants()}catch(e){console.error(e);note.textContent=e?.message||'Не удалось изменить лайк. Попробуйте ещё раз.'}finally{btn.disabled=false}}
async function loadDailyVote(){const{data,error}=await supabase.rpc('get_daily_vote',{p_voter_key:voterKey});if(error){console.error(error);return}currentDailyVote=data||null}
async function loadParticipants(){const{data,error}=await supabase.from('participants').select('*').eq('status','approved').order('vote_count',{ascending:false});if(error){console.error(error);return}participants=data||[];await loadDailyVote();renderGallery();renderLeaderboard();const count=document.querySelector('#participantCount');if(count)count.textContent=participants.length}
const menuToggle=document.querySelector('.menu-toggle');
const mainNav=document.querySelector('#mainNav');
function closeMobileMenu(){if(mainNav){mainNav.classList.remove('mobile-open');menuToggle?.setAttribute('aria-expanded','false');}}
function toggleMobileMenu(){if(!mainNav)return;const open=mainNav.classList.toggle('mobile-open');menuToggle?.setAttribute('aria-expanded',String(open));}
if(menuToggle&&mainNav){
  menuToggle.setAttribute('aria-expanded','false');
  menuToggle.addEventListener('click',toggleMobileMenu);
  mainNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMobileMenu));
  document.addEventListener('click',e=>{if(window.innerWidth<=800&&!mainNav.contains(e.target)&&!menuToggle.contains(e.target))closeMobileMenu()});
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMobileMenu()});
  window.addEventListener('resize',()=>{if(window.innerWidth>800)closeMobileMenu()});
}
document.querySelector('#filterBtn').addEventListener('click',()=>document.querySelector('#filterMenu').classList.toggle('open'));
document.querySelectorAll('#filterMenu button').forEach(b=>b.addEventListener('click',()=>{currentFilter=b.dataset.filter;document.querySelector('#filterMenu').classList.remove('open');document.querySelector('#filterBtn').innerHTML=b.textContent+' <span>⌄</span>';renderGallery()}));
document.querySelector('#entryForm').addEventListener('submit',async e=>{e.preventDefault();note.textContent='Отправляем фотографию…';const form=e.currentTarget,file=form.photo.files[0];if(!file){note.textContent='Выберите фотографию.';return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){note.textContent='Допустимы JPG, PNG и WEBP.';return}if(file.size>10*1024*1024){note.textContent='Файл должен быть не больше 10 МБ.';return}const ext=file.name.split('.').pop().toLowerCase(),path='submissions/'+crypto.randomUUID()+'.'+ext;const upload=await supabase.storage.from('contest-photos').upload(path,file,{contentType:file.type,upsert:false});if(upload.error){note.textContent='Не удалось загрузить фото: '+upload.error.message;return}const fd=new FormData(form);if(!fd.get('personal_data_consent')){note.textContent='Необходимо дать согласие на обработку персональных данных.';return}const {error}=await supabase.from('participants').insert({participant_name:fd.get('name'),participant_surname:fd.get('surname'),bird_name:fd.get('bird'),breed:fd.get('breed'),category:fd.get('category'),contact_phone:fd.get('phone'),contact_email:fd.get('email')||null,personal_data_consent:true,personal_data_consent_at:new Date().toISOString(),description:fd.get('story')||null,photo_path:path,status:'pending',vote_count:0});if(error){await supabase.storage.from('contest-photos').remove([path]);note.textContent='Не удалось сохранить заявку: '+error.message;return}form.reset();note.textContent='Спасибо! Заявка сохранена и появится в галерее после проверки модератором.'});
renderGallery();renderLeaderboard();loadParticipants();
async function loadSponsors(){
  const section=document.querySelector('#sponsors'),grid=document.querySelector('#sponsorsGrid');
  if(!section||!grid)return;
  const {data:settings,error:settingsError}=await supabase.from('contest_settings').select('sponsors_enabled').eq('id',true).maybeSingle();
  if(settingsError||!settings?.sponsors_enabled){section.style.display='none';return}
  const {data,error}=await supabase.from('sponsors').select('id,sponsor_name,description,website_url,photo_path,is_active,sort_order').eq('is_active',true).order('sort_order',{ascending:true}).order('created_at',{ascending:true});
  if(error){console.error(error);section.style.display='none';return}
  if(!data?.length){section.style.display='none';return}
  grid.innerHTML=data.map(s=>'<article class="sponsor-card"><a class="sponsor-link" href="'+escapeHtml(s.website_url)+'" target="_blank" rel="noopener noreferrer"><div class="sponsor-media">'+(s.photo_path?'<img loading="lazy" src="'+publicPhotoUrl(s.photo_path)+'" alt="'+escapeHtml(s.sponsor_name)+'">':'<div class="sponsor-placeholder">🐤</div>')+'</div><div class="sponsor-body"><h3>'+escapeHtml(s.sponsor_name)+'</h3>'+(s.description?'<p>'+escapeHtml(s.description)+'</p>':'')+'<span class="sponsor-more">Перейти на сайт спонсора →</span></div></a></article>').join('');
  section.style.display='block';
}
async function loadWinners(){try{const{data,error}=await supabase.functions.invoke('judge-api',{body:{action:'winners'}});if(error||!data?.enabled){document.querySelector('#winners').style.display='none';document.querySelector('#winnersNav').style.display='none';return}document.querySelector('#winners').style.display='block';document.querySelector('#winnersNav').style.display='inline-flex';const g=document.querySelector('#winnersGrid');g.innerHTML=(data.items||[]).map((p,i)=>'<article class="winner-card"><div class="winner-place">Место '+(i+1)+'</div><img src="'+publicPhotoUrl(p.photo_path)+'" alt="'+escapeHtml(p.bird_name||'')+'"><div class="winner-body"><h3>'+escapeHtml(p.bird_name||'Без имени')+'</h3><p>'+escapeHtml(p.participant_name||'Участник')+' · '+escapeHtml(p.category||'')+'</p><strong>'+p.judge_average+'/10</strong><span>'+p.total_scores+' оценок жюри · '+p.vote_count+' голосов зрителей</span></div></article>').join('')||'<div class="empty">Итоги жюри пока не опубликованы.</div>'}catch(e){console.error(e)}}

async function loadVisitStats(){const{data,error}=await supabase.rpc('get_site_visit_stats');if(error){console.error(error);return}const today=document.querySelector('#visitsToday'),total=document.querySelector('#visitsTotal');if(today)today.textContent=Number(data?.today||0).toLocaleString('ru-RU');if(total)total.textContent=Number(data?.total||0).toLocaleString('ru-RU')}
async function registerSiteVisit(){const{error}=await supabase.rpc('record_site_visit',{p_visitor_key:voterKey});if(error)console.error(error);await loadVisitStats()}
function startVisitorPresence(){const online=document.querySelector('#visitorsOnline');if(!online)return;const channel=supabase.channel('site-presence',{config:{presence:{key:voterKey}}});channel.on('presence',{event:'sync'},()=>{online.textContent=String(Object.keys(channel.presenceState()).length)});channel.subscribe(async status=>{if(status==='SUBSCRIBED'){await channel.track({online_at:new Date().toISOString()})}});window.addEventListener('beforeunload',()=>{channel.untrack()})}
window.refreshSponsorsSection=loadSponsors;
loadWinners();
loadSponsors();
registerSiteVisit();
startVisitorPresence();
