import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const SUPABASE_URL='https://gqwhafobiikhhusryqsz.supabase.co';
const SUPABASE_KEY='sb_publishable_GH4ld1I2zmd9fM2MpjfjKg_z_OB94Uj';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const TEST_PHOTOS=[
{id:'demo-1',name:'Солнечный Ричи',author:'Елена М.',category:'Портрет',votes:124,image:'https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85'},
{id:'demo-2',name:'Первый полёт',author:'Игорь П.',category:'В полёте',votes:98,image:'https://images.unsplash.com/photo-1522926193341-e9ffd686c60f?auto=format&fit=crop&w=900&q=85'},
{id:'demo-3',name:'Жёлтая улыбка',author:'Марина К.',category:'Домашний любимец',votes:87,image:'https://images.unsplash.com/photo-1452570053594-1b985d6ea890?auto=format&fit=crop&w=900&q=85'},
{id:'demo-4',name:'Тихое утро',author:'Сергей В.',category:'Портрет',votes:74,image:'https://images.unsplash.com/photo-1444464666168-49d633b86797?auto=format&fit=crop&w=900&q=85'},
{id:'demo-5',name:'На зелёной ветке',author:'Наталья Р.',category:'Домашний любимец',votes:69,image:'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=900&q=85'},
{id:'demo-6',name:'Яркий окрас',author:'Алексей Т.',category:'Яркий окрас',votes:61,image:'https://images.unsplash.com/photo-1501706362039-c6e8096a2f23?auto=format&fit=crop&w=900&q=85'}];
let participants=[],currentFilter='all';
const galleryGrid=document.querySelector('#galleryGrid'),leaderboard=document.querySelector('#leaderboard'),note=document.querySelector('#formNote');
const publicPhotoUrl=p=>supabase.storage.from('contest-photos').getPublicUrl(p).data.publicUrl;
const voterKey=(()=>{let k=localStorage.getItem('canary_voter_key');if(!k){k=crypto.randomUUID();localStorage.setItem('canary_voter_key',k)}return k})();
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function allPhotos(){return [...participants.map(p=>({id:p.id,name:p.bird_name||'Без имени',author:p.participant_name||'Участник',category:p.category||'Общий конкурс',votes:p.vote_count||0,image:publicPhotoUrl(p.photo_path)})),...TEST_PHOTOS]}
function renderGallery(){const list=allPhotos().filter(p=>currentFilter==='all'||p.category===currentFilter);galleryGrid.innerHTML=list.map(p=>`<article class="photo-card"><img loading="lazy" src="${p.image}" alt="${escapeHtml(p.name)}"><div class="photo-body"><div class="photo-meta"><div><div class="photo-title">${escapeHtml(p.name)}</div><div class="photo-category">${escapeHtml(p.author)} · ${escapeHtml(p.category)}</div></div>${p.id.startsWith('demo-')?'':`<button class="vote" data-id="${p.id}">♥ <span>${p.votes}</span></button>`}</div></div></article>`).join('')||'<div class="empty">В этой категории пока нет фотографий.</div>';document.querySelectorAll('.vote').forEach(b=>b.addEventListener('click',()=>vote(b)))}
function renderLeaderboard(){leaderboard.innerHTML=allPhotos().sort((a,b)=>b.votes-a.votes).slice(0,4).map((p,i)=>`<div class="leader"><div class="rank">0${i+1}</div><img loading="lazy" src="${p.image}" alt=""><div><div class="leader-name">${escapeHtml(p.name)}</div><div class="leader-votes">${escapeHtml(p.author)}</div></div><strong>${p.votes} ♥</strong></div>`).join('')}
async function vote(btn){btn.disabled=true;const{error}=await supabase.from('votes').insert({participant_id:btn.dataset.id,voter_key:voterKey});if(error){note.textContent=error.code==='23505'?'Вы уже голосовали за эту фотографию.':'Не удалось принять голос. Попробуйте ещё раз.';btn.disabled=false;return}const p=participants.find(x=>x.id===btn.dataset.id);if(p)p.vote_count=(p.vote_count||0)+1;btn.querySelector('span').textContent=p?.vote_count||1;btn.classList.add('voted');renderLeaderboard()}
async function loadParticipants(){const{data,error}=await supabase.from('participants').select('*').eq('status','approved').order('vote_count',{ascending:false});if(error){console.error(error);return}participants=data||[];renderGallery();renderLeaderboard();const count=document.querySelector('#participantCount');if(count)count.textContent=participants.length+128}
document.querySelector('#filterBtn').addEventListener('click',()=>document.querySelector('#filterMenu').classList.toggle('open'));
document.querySelectorAll('#filterMenu button').forEach(b=>b.addEventListener('click',()=>{currentFilter=b.dataset.filter;document.querySelector('#filterMenu').classList.remove('open');document.querySelector('#filterBtn').innerHTML=`${b.textContent} <span>⌄</span>`;renderGallery()}));
document.querySelector('#entryForm').addEventListener('submit',async e=>{e.preventDefault();note.textContent='Отправляем фотографию…';const form=e.currentTarget,file=form.photo.files[0];if(!file){note.textContent='Выберите фотографию.';return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){note.textContent='Допустимы JPG, PNG и WEBP.';return}if(file.size>10*1024*1024){note.textContent='Файл должен быть не больше 10 МБ.';return}const ext=file.name.split('.').pop().toLowerCase(),path=`submissions/${crypto.randomUUID()}.${ext}`;const upload=await supabase.storage.from('contest-photos').upload(path,file,{contentType:file.type,upsert:false});if(upload.error){note.textContent='Не удалось загрузить фото: '+upload.error.message;return}const fd=new FormData(form),{error}=await supabase.from('participants').insert({participant_name:fd.get('name'),bird_name:fd.get('bird'),category:fd.get('category'),description:fd.get('story')||null,photo_path:path,status:'pending',vote_count:0});if(error){await supabase.storage.from('contest-photos').remove([path]);note.textContent='Не удалось сохранить заявку: '+error.message;return}form.reset();note.textContent='Спасибо! Заявка сохранена и появится в галерее после проверки модератором.'});
renderGallery();renderLeaderboard();loadParticipants();